/************/
/* SEQUENCE */
/************/
DROP SEQUENCE DB_BBS_SEQ;
DROP SEQUENCE DB_BBS_ATTACH_SEQ;
DROP SEQUENCE DB_BLOCK_SEQ;
DROP SEQUENCE DB_BLOCK_TEMPLATE_SEQ;
DROP SEQUENCE DB_BOARD_SEQ;
DROP SEQUENCE DB_MENU_SEQ;
DROP SEQUENCE DB_REPLY_SEQ;
DROP SEQUENCE DB_STAT_SEQ;
DROP SEQUENCE DB_SUBSCRIBE_SEQ;
DROP SEQUENCE DB_TEMPLATE_SEQ;
DROP SEQUENCE DB_USER_SEQ;

CREATE SEQUENCE DB_BBS_SEQ;
CREATE SEQUENCE DB_BBS_ATTACH_SEQ;
CREATE SEQUENCE DB_BLOCK_SEQ;
CREATE SEQUENCE DB_BLOCK_TEMPLATE_SEQ;
CREATE SEQUENCE DB_BOARD_SEQ;
CREATE SEQUENCE DB_MENU_SEQ;
CREATE SEQUENCE DB_REPLY_SEQ;
CREATE SEQUENCE DB_STAT_SEQ;
CREATE SEQUENCE DB_SUBSCRIBE_SEQ;
CREATE SEQUENCE DB_TEMPLATE_SEQ;
CREATE SEQUENCE DB_USER_SEQ;

/**********************/
/* SAMPLE DATA INSERT */
/**********************/

/* DB_USER */
INSERT INTO db_user (userNo, userEMail, userName, userPassword, blogTitle, blogAddress) VALUES (db_user_seq.nextval, 'admin@decoblo.com', '관리자', 'admin', '관리자님의 블로그', 'admin');
INSERT INTO db_user (userNo, userEMail, userName, userPassword, blogTitle, blogAddress) VALUES (db_user_seq.nextval, 'test@test.com', '테스트', 'test', '테스트님의 블로그', 'test');

/* DB_MEMU */
INSERT INTO DB_MENU (MENUNO, MENUUSERNO, MENUNAME, MENUPARENT, MENUDEPTH, MENUSEQ, MENUVISIBLE) VALUES (1, 1, 'Menu1', 1, 0, 0, 1);
INSERT INTO DB_MENU (MENUNO, MENUUSERNO, MENUNAME, MENUPARENT, MENUDEPTH, MENUSEQ, MENUVISIBLE) VALUES (2, 1, 'SubMenu1', 1, 1, 1, 1);
INSERT INTO DB_MENU (MENUNO, MENUUSERNO, MENUNAME, MENUPARENT, MENUDEPTH, MENUSEQ, MENUVISIBLE) VALUES (3, 1, 'Submenu2', 1, 1, 2, 1);
INSERT INTO DB_MENU (MENUNO, MENUUSERNO, MENUNAME, MENUPARENT, MENUDEPTH, MENUSEQ, MENUVISIBLE) VALUES (4, 1, 'Menu2', 4, 0, 0, 1);
INSERT INTO DB_MENU (MENUNO, MENUUSERNO, MENUNAME, MENUPARENT, MENUDEPTH, MENUSEQ, MENUVISIBLE) VALUES (5, 1, 'Submenu1', 4, 1, 1, 1);
INSERT INTO DB_MENU (MENUNO, MENUUSERNO, MENUNAME, MENUPARENT, MENUDEPTH, MENUSEQ, MENUVISIBLE) VALUES (6, 1, 'Menu3', 6, 0, 0, 1);
